export const languages = [
  { value: "abap", label: "ABAP" },
  { value: "apex", label: "Apex" },
  { value: "azcli", label: "Azure CLI" },
  { value: "bat", label: "Batch" },
  { value: "bicep", label: "Bicep" },
  { value: "cameligo", label: "Cameligo" },
  { value: "clojure", label: "Clojure" },
  { value: "coffeescript", label: "CoffeeScript" },
  { value: "cpp", label: "C++" },
  { value: "csharp", label: "C#" },
  { value: "csp", label: "Content Security Policy" },
  { value: "css", label: "CSS" },
  { value: "dart", label: "Dart" },
  { value: "dockerfile", label: "Dockerfile" },
  { value: "ecl", label: "ECL" },
  { value: "elixir", label: "Elixir" },
  { value: "flow9", label: "Flow9" },
  { value: "fsharp", label: "F#" },
  { value: "go", label: "Go" },
  { value: "graphql", label: "GraphQL" },
  { value: "handlebars", label: "Handlebars" },
  { value: "hcl", label: "HCL" },
  { value: "html", label: "HTML" },
  { value: "ini", label: "INI" },
  { value: "java", label: "Java" },
  { value: "javascript", label: "JavaScript" },
  { value: "julia", label: "Julia" },
  { value: "kotlin", label: "Kotlin" },
  { value: "less", label: "Less" },
  { value: "lexon", label: "Lexon" },
  { value: "liquid", label: "Liquid" },
  { value: "lua", label: "Lua" },
  { value: "m3", label: "M3" },
  { value: "markdown", label: "Markdown" },
  { value: "mips", label: "MIPS" },
  { value: "msdax", label: "MSDAX" },
  { value: "mysql", label: "MySQL" },
  { value: "objective-c", label: "Objective-C" },
  { value: "pascal", label: "Pascal" },
  { value: "pascaligo", label: "Pascaligo" },
  { value: "perl", label: "Perl" },
  { value: "pgsql", label: "PostgreSQL" },
  { value: "php", label: "PHP" },
  { value: "plaintext", label: "Plain Text" },
  { value: "postiats", label: "ATS" },
  { value: "powerquery", label: "Power Query" },
  { value: "powershell", label: "PowerShell" },
  { value: "proto", label: "Protobuf" },
  { value: "pug", label: "Pug" },
  { value: "python", label: "Python" },
  { value: "qsharp", label: "Q#" },
  { value: "r", label: "R" },
  { value: "razor", label: "Razor" },
  { value: "redis", label: "Redis" },
  { value: "redshift", label: "Redshift" },
  { value: "restructuredtext", label: "reStructuredText" },
  { value: "ruby", label: "Ruby" },
  { value: "rust", label: "Rust" },
  { value: "sb", label: "Small Basic" },
  { value: "scala", label: "Scala" },
  { value: "scheme", label: "Scheme" },
  { value: "scss", label: "SCSS" },
  { value: "shell", label: "Shell" },
  { value: "sol", label: "Solidity" },
  { value: "sparql", label: "SPARQL" },
  { value: "sql", label: "SQL" },
  { value: "st", label: "Structured Text" },
  { value: "swift", label: "Swift" },
  { value: "systemverilog", label: "SystemVerilog" },
  { value: "tcl", label: "TCL" },
  { value: "twig", label: "Twig" },
  { value: "typescript", label: "TypeScript" },
  { value: "vb", label: "VB.NET" },
  { value: "xml", label: "XML" },
  { value: "yaml", label: "YAML" }
];